'use client';

/**
 * Legal Page
 * 
 * Privacy Policy, Terms of Service, Accessibility, and Health Disclaimer.
 * Last Updated: March 2026
 */

import { ChevronLeft, ChevronDown, ChevronUp } from 'lucide-react';
import { useRouter } from 'next/navigation';
import { useState } from 'react';
import { HamburgerMenu } from '@/components/v2/HamburgerMenu';

interface LegalSection {
  id: string;
  title: string;
  paragraphs: string[];
}

const legalSections: LegalSection[] = [
  {
    id: 'health-disclaimer',
    title: 'Health & Nutrition Disclaimer',
    paragraphs: [
      'This application provides nutritional information, health scores, allergen detection, and food processing analysis for informational and educational purposes only. The content generated by this application does not constitute medical advice, diagnosis, or treatment.',
      'AI-Generated Analysis: All health scores, ingredient analysis, allergen detection, and nutritional assessments are generated by artificial intelligence. While we strive for accuracy, AI analysis may contain errors, omissions, or misinterpretations of product labels.',
      'Allergen Warnings: Allergen detection is based on AI interpretation of product labels and may not identify all allergens, cross-contamination risks, or trace ingredients. Individuals with food allergies or sensitivities should always read the physical product label and consult with a healthcare professional before consuming any product.',
      'Not a Substitute for Professional Advice: Always consult a qualified healthcare provider, registered dietitian, or allergist for advice regarding your diet, nutrition, food allergies, or any health condition. Do not disregard professional medical advice or delay seeking it based on information provided by this application.',
      'No Liability: Normal Labs LLC is not liable for any adverse health effects, allergic reactions, or other consequences resulting from reliance on the information provided by this application.',
    ],
  },
  {
    id: 'privacy-policy',
    title: 'Privacy Policy',
    paragraphs: [
      'Your privacy is a priority. This section describes how the Product Scanner application handles your data.',
      'Camera Access: This application requests access to your device camera solely for the purpose of scanning product labels. Images captured are processed to extract product information and are not stored on our servers after processing is complete.',
      'Local Storage: This application uses your browser\'s local storage to save scan history, incomplete scan state, and application preferences. This data remains on your device and is not transmitted to our servers. You can clear this data at any time through the History page or your browser settings.',
      'Product Database: Extracted product information (product names, ingredients, nutrition facts, barcodes) is stored in our database to improve scan accuracy and enable caching for faster results. This data is not linked to any personal identifier.',
      'Cookies: This application does not use cookies for tracking or analytics purposes.',
      'Third-Party Services: This application uses the following third-party services: Google Vertex AI (Gemini) for image analysis and text extraction; Supabase for product data storage; MongoDB for product caching; Buy Me a Coffee for optional donation support; and Google AdSense for displaying advertisements. These services may collect certain technical data (such as IP address or device type) in accordance with their own privacy policies. We encourage you to review the privacy policies of these third-party providers.',
      'Advertising: This application displays advertisements served by Google AdSense. Google may use cookies and similar technologies to serve ads based on your prior visits to this or other websites. You can opt out of personalized advertising by visiting Google\'s Ads Settings (https://adssettings.google.com). For more information about how Google uses data, visit Google\'s Privacy & Terms page (https://policies.google.com/technologies/partner-sites).',
      'Data Collection: We do not collect personal information such as your name, email address, or location. No account creation is required to use this application. We do not sell or share any data with third parties beyond the service providers listed above.',
      'Data Retention: Product scan data stored in our database is retained indefinitely to improve the service. Local storage data on your device persists until you clear it manually.',
    ],
  },
  {
    id: 'terms-of-use',
    title: 'Terms of Use',
    paragraphs: [
      'By accessing and using the Product Scanner application, you agree to the following terms:',
      'Service Purpose: This application is provided for informational and entertainment purposes only. It uses artificial intelligence to analyze product labels and provide nutritional insights, health scores, allergen detection, and food processing assessments. It is not intended to replace professional dietary, medical, or nutritional advice.',
      'Accuracy: While we strive for accuracy, the information provided is generated by AI and may contain errors. Product formulations change over time, and the information displayed may not reflect the most current product label. Always verify information against the physical product label.',
      'Assumption of Risk: You acknowledge that you use this application at your own risk. You are solely responsible for any decisions you make based on the information provided, including dietary choices and allergen avoidance.',
      'Intellectual Property: All text, code, design, and AI-generated analysis are the intellectual property of Normal Labs LLC. Product names, logos, and brands displayed in scan results are the property of their respective owners.',
      'Prohibited Use: You may not use this application to generate misleading health claims, to reverse-engineer the AI analysis system, or for any unlawful purpose.',
      'Service Availability: This application is provided "as is" without warranties of any kind, express or implied. We do not guarantee uninterrupted availability, accuracy of results, or fitness for a particular purpose. We reserve the right to modify or discontinue the service at any time without notice.',
      'Limitation of Liability: To the fullest extent permitted by law, Normal Labs LLC shall not be liable for any direct, indirect, incidental, consequential, or punitive damages arising from your use of this application, including but not limited to health-related decisions made based on the information provided.',
    ],
  },
  {
    id: 'accessibility',
    title: 'Accessibility',
    paragraphs: [
      'We are committed to ensuring digital accessibility for all users. This application is designed to be usable, understandable, and navigable for people of all abilities.',
      'Standards: We aim to follow WCAG 2.1 Level AA guidelines by using semantic HTML, maintaining sufficient color contrast, and supporting keyboard navigation throughout the application.',
      'Camera Dependency: The core scanning feature requires camera access, which may present challenges for users with certain disabilities. We are exploring alternative input methods such as manual barcode entry for future releases.',
      'Limitations: While the application itself is designed with accessibility in mind, AI-generated content (such as health explanations and ingredient analysis) may not always meet optimal readability standards.',
      'Feedback: If you encounter any accessibility barriers while using this application, please contact us at contact@normallabs.io. We welcome your feedback and are committed to improving the experience for all users.',
    ],
  },
  {
    id: 'copyright',
    title: 'Copyright',
    paragraphs: [
      '\u00A9 2026 Normal Labs LLC. All rights reserved. All product names, logos, and brands are property of their respective owners.',
    ],
  },
  {
    id: 'contact',
    title: 'Contact',
    paragraphs: [
      'For questions about these policies or the application, contact us at contact@normallabs.io.',
    ],
  },
];

function SectionAccordion({ section }: { section: LegalSection }) {
  const [open, setOpen] = useState(false);

  return (
    <div className="border-b border-border last:border-b-0">
      <button
        onClick={() => setOpen(!open)}
        className="w-full flex items-center justify-between py-4 text-left"
        aria-expanded={open}
      >
        <span className="text-sm font-semibold text-foreground">{section.title}</span>
        {open ? (
          <ChevronUp className="w-4 h-4 text-muted-foreground shrink-0" />
        ) : (
          <ChevronDown className="w-4 h-4 text-muted-foreground shrink-0" />
        )}
      </button>
      {open && (
        <div className="pb-4 space-y-3">
          {section.paragraphs.map((p, i) => (
            <p key={i} className="text-xs text-muted-foreground leading-relaxed">
              {p}
            </p>
          ))}
        </div>
      )}
    </div>
  );
}

export default function LegalPage() {
  const router = useRouter();

  return (
    <div className="min-h-screen bg-background flex justify-center">
      <div className="max-w-md w-full min-h-screen bg-background shadow-xl">
        {/* Header */}
        <div className="flex items-center justify-between px-5 py-4 border-b border-border">
          <div className="flex items-center gap-3">
            <button
              onClick={() => router.back()}
              className="w-9 h-9 rounded-full bg-secondary flex items-center justify-center hover:bg-secondary/80 transition-colors"
            >
              <ChevronLeft className="w-5 h-5 text-foreground" />
            </button>
            <h1 className="text-lg font-semibold text-foreground">Legal</h1>
          </div>
          <HamburgerMenu />
        </div>

        {/* Content */}
        <div className="px-5 py-4 pb-24">
          <p className="text-xs text-muted-foreground mb-4">Last Updated: March 2026</p>

          <div className="bg-card rounded-2xl border border-border px-4">
            {legalSections.map((section) => (
              <SectionAccordion key={section.id} section={section} />
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}
