/**
 * InsightsDisplay Component
 * 
 * Renders analysis results for all detected products with tier-aware display.
 * Premium tier: Shows all five insight categories
 * Free tier: Shows only the selected dimension
 * 
 * Requirements: 4.3, 4.4, 4.5, 5.4, 11.2, 11.5
 */

import { AnalysisResult, InsightCategory } from '@/lib/types';
import SmartBadge from './SmartBadge';

interface InsightsDisplayProps {
  results: AnalysisResult;
  tier?: 'free' | 'premium';
  dimension?: InsightCategory;
  fromCache?: boolean | null;
}

export default function InsightsDisplay({ results, tier = 'premium', dimension, fromCache }: InsightsDisplayProps) {
  // Handle empty results
  if (!results || !results.products || results.products.length === 0) {
    return (
      <div className="text-center py-8 px-4">
        <p className="text-gray-600 text-lg mb-2">
          No products detected
        </p>
        <p className="text-gray-500 text-sm">
          Please capture a clearer image of the product and try again.
        </p>
      </div>
    );
  }

  // Determine which categories to display
  const categoriesToDisplay: InsightCategory[] =
    tier === 'free' && dimension
      ? [dimension]
      : ['health', 'preservatives', 'allergies', 'sustainability', 'carbon'];

  return (
    <div 
      className="w-full max-h-[70vh] overflow-y-auto px-4 py-6 space-y-8"
      role="region"
      aria-label="Product analysis results"
    >
      {results.products.map((product, productIndex) => (
        <div 
          key={`${product.productName}-${productIndex}`}
          className="bg-white rounded-lg shadow-md p-5 border border-gray-200"
        >
          {/* Product name header */}
          <h2 className="text-2xl font-bold text-gray-800 mb-4 pb-3 border-b border-gray-300">
            {product.productName}
          </h2>

          {/* Data source badge */}
          {fromCache !== null && fromCache !== undefined && (
            <div className={`mb-4 rounded-lg border ${
              fromCache 
                ? 'bg-green-50 border-green-200' 
                : 'bg-blue-50 border-blue-200'
            }`}>
              <div className="p-3">
                <div className="flex items-start gap-3">
                  <span className="text-2xl flex-shrink-0" role="img" aria-label={fromCache ? 'cached' : 'fresh'}>
                    {fromCache ? '⚡' : '🤖'}
                  </span>
                  <div className="flex-1 min-w-0">
                    <p className={`text-sm font-semibold mb-1 ${
                      fromCache ? 'text-green-800' : 'text-blue-800'
                    }`}>
                      {fromCache ? 'Cached Data' : 'Fresh AI Analysis'}
                    </p>
                    <p className={`text-xs leading-relaxed ${
                      fromCache ? 'text-green-700' : 'text-blue-700'
                    }`}>
                      {fromCache 
                        ? 'Retrieved from MongoDB cache (instant response)' 
                        : 'Generated by Gemini 2.0 Flash AI model'}
                    </p>
                  </div>
                </div>
              </div>
              
              {/* Data flow details */}
              <div className={`border-t px-3 py-2.5 text-xs ${
                fromCache 
                  ? 'bg-green-100/50 border-green-200 text-green-700' 
                  : 'bg-blue-100/50 border-blue-200 text-blue-700'
              }`}>
                <div className="flex items-start gap-2">
                  <span className="font-semibold whitespace-nowrap">Data Flow:</span>
                  <span className="break-words">
                    {fromCache ? (
                      <>Browser → API → MongoDB Cache → Response</>
                    ) : (
                      <>Browser → API → Gemini AI → MongoDB Cache → Supabase → Response</>
                    )}
                  </span>
                </div>
              </div>
            </div>
          )}

          {/* Tier indicator */}
          {tier === 'free' && (
            <div className="mb-4 p-3 bg-blue-50 border border-blue-200 rounded-lg">
              <p className="text-sm text-blue-800">
                🆓 Free tier: Showing {dimension} analysis only.{' '}
                <span className="font-medium">Upgrade to Premium</span> for all 5 dimensions.
              </p>
            </div>
          )}

          {/* Render SmartBadge for each category */}
          <div className="space-y-3">
            {categoriesToDisplay.map((category) => {
              const insight = product.insights[category];
              
              // Skip if insight doesn't exist (shouldn't happen with proper validation)
              if (!insight) return null;
              
              return (
                <SmartBadge
                  key={category}
                  category={category}
                  rating={insight.rating}
                  explanation={insight.explanation}
                />
              );
            })}
          </div>
        </div>
      ))}
    </div>
  );
}
